server:
  port: 8080
spring.cloud.stream:
  function:
    definition: orderEventPublisher;paymentEventConsumer
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    paymentEventConsumer-in-0:
      destination: payment-events